config/routes.rb
SampleApp::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  
  
  match '/smartphones', to: 'dynamic_pages_products#smartphones'
  match '/tablets', 	to: 'dynamic_pages_products#tablets'
  match '/accessories', to: 'dynamic_pages_products#accessories'

  resources :products  
  
  match '/aviso',    to: 'static_pages#aviso'
  match '/uso',    to: 'static_pages#uso'
  match '/sitio',    to: 'static_pages#sitio'
  match '/sucursales',    to: 'static_pages#sucursales'
    

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/dynamic_pages_products_controller.rb
class DynamicPagesProductsController < ApplicationController
  def smartphones
	#@smartphones = Product.select("name, price, mark, description, image").where("category = 1")
	@smartphones = Product.where("category = 1").paginate(page: params[:page])
	if params[:mark]
		@smartphones = Product.where("category = 1 AND mark = ?", params[:mark]).paginate(page: params[:page])
	end
	if params[:model]
		@smartphones = Product.where("category = 1 AND model = ?", params[:model]).paginate(page: params[:page])
	end
	if params[:start_price]
		@smartphones = Product.where(:category => 1, :price => (params[:start_price].to_i)..(params[:end_price].to_i))
		.order("price ASC")
		.paginate(page: params[:page])
		
	end
  end

  def tablets
	 #@tablets = Product.select("name, price, model, description").where("category = 2")
	 @tablets = Product.where("category = 3").paginate(page: params[:page])
	 if params[:mark]
	   @tablets = Product.where("category = 3 AND mark = ?", params[:mark]).paginate(page: params[:page])
	 end
	 if params[:model]
    @tablets = Product.where("category = 3 AND model LIKE ?", "%#{params[:model]}%").paginate(page: params[:page])
	 end
	 if params[:start_price]
    @tablets = Product.where(:category => 3, :price => (params[:start_price].to_i)..(params[:end_price].to_i))
    .order("price ASC")
    .paginate(page: params[:page])
   end
  end

  def accessories
    #@accessories = Product.select("name, price, model, description").where("category = 3")
    @accessories = Product.where("category = 4 OR category = 2").paginate(page: params[:page])
    if params[:mark]
      @accessories = Product.where(:category => [2,4], :mark => params[:mark]).paginate(page: params[:page])
    end
    if params[:category]
      @accessories = Product.where("category = ? ", params[:category]).paginate(page: params[:page])
    end
    if params[:start_price]
      @accessories = Product.where(:category => [2,4], :price => (params[:start_price].to_i)..(params[:end_price].to_i))
      .order("price ASC")
      .paginate(page: params[:page])
    end
  end
end

app/helpers/dynamic_pages_products_helper.rb
module DynamicPagesProductsHelper
end

app/views/dynamic_pages_products/accessories.html.erb
<% provide(:title, 'Accessories') %>
<!--<h1>DynamicPagesProducts#accessories</h1>
<p>Find me in app/views/dynamic_pages_products/accessories.html.erb</p>
-->

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Marcas</li>
              <li><%= link_to "Nokia", accessories_path(:mark => "Nokia") %></li>
              <li><%= link_to "Samsung", accessories_path(:mark => "Samsung") %></li>
              <li><%= link_to "Apple", accessories_path(:mark => "Apple") %></li>
              <li><%= link_to "Blackberry", accessories_path(:mark => "Blackberry") %></li>
              <li><%= link_to "Sony", accessories_path(:mark => "Sony") %></li>
              <li class="nav-header">Tipos</li>
              <li><%= link_to "Accesorios para Tablets", accessories_path(:category => "4") %></li>
              <li><%= link_to "Accesorios para Smartphones", accessories_path(:category => "2") %></li>
              <li class="nav-header">Precios</li>
              <li><%= link_to "$150 a $250", accessories_path(:start_price => "150", :end_price => "250") %></li>
              <li><%= link_to "$250 a $350", accessories_path(:start_price => "250", :end_price => "350") %></li>
              <li><%= link_to "$350 a $450", accessories_path(:start_price => "350", :end_price => "450") %></li>
              <li><%= link_to "Mayor a $450", accessories_path(:start_price => "450", :end_price => "2500") %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <br/><br/><br/>
          <ul id="homeItems">
		  <% @accessories.each do |accessory| %>
		  	<li>
			<div class="catItem">
				<div class="itemMedia">
					<!--<img src="<%= raw accessory.image %>" style="height:110px;width:160px;border-width:0px;"/>
					<%= image_tag accessory.image, size:"160x110"%>-->
					<%= link_to image_tag(accessory.image), line_items_path(:product_id => accessory), :method => :post%>
				</div>
				<div class="itemInfo">
					<h3><%= accessory.mark%> <%=accessory.name%> <%= accessory.model%></h3>
					<br /> <br />
					<div class="precio">
						<div>  $
							<span><%= accessory.price %></span>
						</div>
						<br /> <br />
						<p><%= link_to "Más detalles", product_path(accessory.id), class: "btn btn-primary btn-large"%></p>
						<!--<%= button_to 'Agregar al carrito', line_items_path(:product_id => accessory), class: "btn btn-primary btn-large"%>-->
						<%= link_to  line_items_path(:product_id => accessory), class: "btn btn-primary btn-large", :method => :post do%>
						<i class="icon-shopping-cart icon-white"></i> Agregar al carrito 
						<% end%>
					</div>
				</div>
			</div> <!--/catItem-->
			</li>
			<% end %>
		  </ul><!--/homeItems-->
		  
		  <% if @accessories.empty? %>
			<div class="aviso">
			<em> No tenemos existencias de esta marca por el momento </em>
			</div>
		  <% end %>
		</div> <!--/row-fluid-->
      <hr>
	<%= will_paginate @accessories%>
</div><!--/.fluid-container-->

app/views/dynamic_pages_products/smartphones.html.erb
<% provide(:title, 'SmartPhones') %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<div class="well sidebar-nav">
            	<ul class="nav nav-list">
              		<li class="nav-header">Marcas</li>
              		<li ><%= link_to "Nokia", smartphones_path(:mark => "Nokia") %></li>
              		<li><%= link_to "Samsung", smartphones_path(:mark => "Samsung") %></li>
              		<li><%= link_to "Apple", smartphones_path(:mark => "Apple") %></li>
              		<li><%= link_to "Blackberry", smartphones_path(:mark => "Blackberry") %></li>
              		<li><%= link_to "Sony", smartphones_path(:mark => "Sony") %></li>
              		<li class="nav-header">Modelos</li>
              		<li><%= link_to "800", smartphones_path(:model => "800") %></li>
              		<li><%= link_to "710", smartphones_path(:model => "710") %></li>
              		<li><%= link_to "N9", smartphones_path(:model => "N9") %></li>
              		<li><%= link_to "S II", smartphones_path(:model => "S II") %></li>
              		<li><%= link_to "Ace", smartphones_path(:model => "Ace") %></li>
              		<li><%= link_to "4", smartphones_path(:model => "4") %></li>
              		<li class="nav-header">Precios</li>
		            <li><%= link_to "1500 a 2500", smartphones_path(:start_price => "1500", :end_price => "2500") %></li>
		            <li><%= link_to "2500 a 3500", smartphones_path(:start_price => "2500", :end_price => "3500") %></li>
		            <li><%= link_to "3500 a 4500", smartphones_path(:start_price => "3500", :end_price => "4500") %></li>
					<li><%= link_to "Mayor a $4500", smartphones_path(:start_price => "4500", :end_price => "16000") %></li>
            	</ul>
			</div><!--/.well -->
        </div><!--/span-->
        <!--<div class="span10">-->
        	<br /><br /><br />        
          <ul id="homeItems">
		  <% @smartphones.each do |smartphone| %>
		  	<li>
			<div class="catItem">
				<div class="itemMedia">
					<!--<img src="<%= raw smartphone.image %>" style="height:110px;width:160px;border-width:0px;"/>-->
					<%= link_to image_tag(smartphone.image, :size => "110x110"), line_items_path(:product_id => smartphone), :method => :post%>
				</div>
				<div class="itemInfo">
					<h3><%= smartphone.mark%> <%=smartphone.name%> <%= smartphone.model%></h3>
					<div class="precio">
						<div>  $
							<span><%= smartphone.price %></span>
						</div>
						<!--<p><a class="btn btn-primary btn-large" href="#">Más Detalles a  articulo <%= smartphone.id%></a></p>--> 
						<p><%= link_to "Más detalles", product_path(smartphone.id), class: "btn btn-primary btn-large"%></p>
						<!--<%= button_to 'Agregar al carrito', line_items_path(:product_id => smartphone), class: "btn btn-primary btn-large"%>-->
						<%= link_to  line_items_path(:product_id => smartphone), class: "btn btn-primary btn-large", :method => :post do%>
						<i class="icon-shopping-cart icon-white"></i> Agregar al carrito 
            			<% end%>
					</div>
				</div>
				<!--
				<div class="description">
					<%= smartphone.description%>
				</div>
				-->
			</div> <!--/catItem-->
			</li>
			<% end %>
		  </ul><!--/homeItems-->
		  
		  <% if @smartphones.empty? %>
			<div class="aviso">
			<em> No tenemos existencias de esta marca por el momento </em>
			</div>
		  <% end %>
		</div> <!--/row-fluid-->
      <hr>
	<%= will_paginate @smartphones%>
</div><!--/.fluid-container-->

app/views/dynamic_pages_products/tablets.html.erb
<% provide(:title, 'Tablets') %>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Marcas</li>
              <li><%= link_to "Nokia", tablets_path(:mark => "Nokia") %></li>
              <li><%= link_to "Samsung", tablets_path(:mark => "Samsung") %></li>
              <li><%= link_to "Apple", tablets_path(:mark => "Apple") %></li>
              <li><%= link_to "Blackberry", tablets_path(:mark => "Blackberry") %></li>
              <li><%= link_to "Sony", tablets_path(:mark => "Sony") %></li>
              <li class="nav-header">Modelos</li>
              <li><%= link_to "Galaxy", tablets_path(:model => "Galaxy") %></li>
              <li><%= link_to "SGPT111", tablets_path(:model => "SGPT111") %></li>
              <li><%= link_to "SGPT132", tablets_path(:model => "SGPT132") %></li>
              <li><%= link_to "PRD-38548", tablets_path(:model => "PRD-38548") %></li>
              <li><%= link_to "ipad", tablets_path(:model => "ipad") %></li>
              <li><%= link_to "770", tablets_path(:model => "770") %></li>
              <li><%= link_to "800", tablets_path(:model => "800") %></li>
              <li class="nav-header">Precios</li>
              <li><%= link_to "$3000 a $4500", tablets_path(:start_price => "3000", :end_price => "4500") %></li>
              <li><%= link_to "$4500 a $6500", tablets_path(:start_price => "4500", :end_price => "6500") %></li>
              <li><%= link_to "$6500 a $8500", tablets_path(:start_price => "6500", :end_price => "8500") %></li>
              <li><%= link_to "Mayor a $8500", tablets_path(:start_price => "8500", :end_price => "16000") %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <br /><br /><br />
          <ul id="homeItems">
		  <% @tablets.each do |tablet| %>
		  	<li>
			<div class="catItem">
				<div class="itemMedia">
					<!--<img src="<%= raw tablet.image %>" style="height:110px;width:160px;border-width:0px;"/>
					<%= image_tag tablet.image, size:"160x110"%>-->
					<%= link_to image_tag(tablet.image), line_items_path(:product_id => tablet), :method => :post%>
				</div>
				<div class="itemInfo">
					<h3><%= tablet.mark%> <%=tablet.name%> <%= tablet.model%></h3>
					<div class="precio">
						<div>  $
							<span><%= tablet.price %></span>
						</div>
						<p><%= link_to "Más detalles", product_path(tablet.id), class: "btn btn-primary btn-large"%></p>
						<!--<%= button_to 'Agregar al carrito', line_items_path(:product_id => tablet), class: "btn btn-primary btn-large"%>-->
						<%= link_to  line_items_path(:product_id => tablet), class: "btn btn-primary btn-large", :method => :post do%>
						<i class="icon-shopping-cart icon-white"></i> Agregar al carrito 
						<% end%>
					</div>
				</div>
			</div> <!--/catItem-->
			</li>
			<% end %>
		  </ul><!--/homeItems-->
		  
		  <% if @tablets.empty? %>
			<div class="aviso">
			<em> No tenemos existencias de esta marca por el momento </em>
			</div>
		  <% end %>
		</div> <!--/row-fluid-->
      <hr>
	<%= will_paginate @tablets%>
</div><!--/.fluid-container-->