config/routes.rb
SampleApp::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  
  
  match '/smartphones', to: 'dynamic_pages_products#smartphones'
  match '/tablets', 	to: 'dynamic_pages_products#tablets'
  match '/accessories', to: 'dynamic_pages_products#accessories'

  resources :products  
  
  match '/aviso',    to: 'static_pages#aviso'
  match '/uso',    to: 'static_pages#uso'
  match '/sitio',    to: 'static_pages#sitio'
  match '/sucursales',    to: 'static_pages#sucursales'
    

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/product.rb
class Product < ActiveRecord::Base
  self.per_page = 6
  attr_accessible :description, :image, :mark, :model, :name, :price, :category
  
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private
  # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mark %><br />
    <%= f.text_field :mark %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.number_field :category %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mark</th>
    <th>Model</th>
    <th>Price</th>
    <th>Description</th>
    <th>Category</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.mark %></td>
    <td><%= product.model %></td>
    <td><%= product.price %></td>
    <td><%= product.description %></td>
    <td><%= product.category %></td>
    <td><%= product.image %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<script type="text/javascript">
	$(function() {
		$('#descripcion p').each(function() {
			var lista = "<ul id='caracteristicas'>";
			var prev = $(this).html();
			var str = prev.replace(/\s([A-Z])/g, ",$1");
			var arreglo = str.split(",");
			for(var i = 0; i < arreglo.length; i++) {
				lista += "<li>" + arreglo[i] + "</li> <br />";
			}
			lista += "</ul>";
			$(this).html(lista);
			
		});
		
		
	});
</script>
<style type="text/css">
	
</style>
<div class="hero-unit">
	<div class="row-fluid">
		<div class="span4">
			<!--<img src="<%= raw @product.image %>" style="height:110px;width:160px;border-width:0px;"/>-->
			<%= image_tag(@product.image, size:"160x110")%>	
		</div>
		<div class="span8 offset2">
			<div class="itemInfo">
				<h3><%= @product.mark%> <%= @product.name%> <%= @product.model%></h3>
				<div class="precio">
					$ <span> <%= @product.price%></span>
				</div>
				<div id="descripcion">
					<p><%= @product.description%></p>
				</div>
			</div>
			<div class="row">
				<%= link_to  line_items_path(:product_id => @product.id), class: "btn btn-primary btn-large", :method => :post do%>
				<i class="icon-shopping-cart icon-white"></i> Agregar al carrito 
				<% end%>
			</div>
		</div>
	</div>
</div>