config/routes.rb
SampleApp::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  
  
  match '/smartphones', to: 'dynamic_pages_products#smartphones'
  match '/tablets', 	to: 'dynamic_pages_products#tablets'
  match '/accessories', to: 'dynamic_pages_products#accessories'

  resources :products  
  
  match '/aviso',    to: 'static_pages#aviso'
  match '/uso',    to: 'static_pages#uso'
  match '/sitio',    to: 'static_pages#sitio'
  match '/sucursales',    to: 'static_pages#sucursales'
    

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  	<br><br>
    Desarrollado por eureka
  </small>
  <nav>
    <ul>
    	<br><br>
      <li><%= link_to "Aviso Privacidad",   aviso_path %></li>
      <li><%= link_to "Condiciones de Uso",   uso_path %></li>	
      <li><%= link_to "Ayuda", help_path %></li>
      <li><%= link_to "SiteMap",   sitio_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header-backup.html.erb
<header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
</header>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!--<%= link_to "sample app", '#', id: "logo" %>-->
		  <div id="logo">
		  <%= link_to image_tag("logo2.png", alt: "eureka", size: "278x100"), root_path %>
		  </div>
          <nav>
            <ul class="nav pull-right">
			  <% if signed_in? %>
			  <!--
              <li><%= link_to "Users", '#' %></li>
              <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
           -->
            <li><%= link_to root_path do%>
            	<i class="icon-user icon-white"></i> <%= current_user.name%>
            <% end%>
            </li>
            <li><%= link_to "Cerrar Sesión", signout_path, method: "delete" %> </li>
          <% else %>
            <li><%= link_to "¿Usuario nuevo? Registrate ahora!", signup_path %></li>
            <li><%= link_to "Iniciar Sesión", signin_path %></li>
          <% end %>
            </ul>
          </nav>
          <!--<div id="carrito_compras">
          	<button class="btn">
          </div>-->
        </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    
	<style type="text/css">
		div.myclass{margin-top:100px}
		body{background-color: #EAECEE}
	</style>
	
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container myclass">
	   <% flash.each do |key,value| %>
		<div class="alert alert-<%=key %>"><%=value%></div>
		<%end%>
		<div class= "wrapper" style="margin-top:6em">
		<ul id="menu-horizontal">
			<li class="btn btn-large btn-primary"><%= link_to "Inicio", root_path %></li>
			<li class="btn btn-large btn-primary"><a href="#">Productos</a>
			<ul>
				<li class="btn btn-large btn-primary"><%= link_to "Smartphones", smartphones_path%></li>
				<li class="btn btn-large btn-primary"><%= link_to "Tablets", 	   tablets_path %></li>
				<li class="btn btn-large btn-primary"><%= link_to "Accesorios",  accessories_path%></li>
			</ul>
			</li>
			<li class="btn btn-large btn-primary"><a href="#">Nosotros</a>
				<ul>
					<li class="btn btn-large btn-primary"><%= link_to "Quienes Somos", about_path %></li>
					<li class="btn btn-large btn-primary"><%= link_to "Contacto", contact_path %></li>
				</ul>
			</li>
			<li class="last btn btn-large btn-primary"><%= link_to "Sucursales", sucursales_path %></li>
		</ul>
		</div>
        <%=yield%>
	  

	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "jquery", "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	   <% flash.each do |key,value| %>
		<div class="alert alert-<%=key %>"><%=value%></div>
		<%end%>
      <%= yield %>
	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/application_backup2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "jquery", "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	   <% flash.each do |key,value| %>
		<div class="alert alert-<%=key %>"><%=value%></div>
		<%end%>
		<div class= "wrapper">
		<ul id="menu-horizontal">
			<li><a href="#">Inicio</a></li>
			<li><a href="#">Productos</a>
			<ul>
				<li><%= link_to "Smartphones", smartphones_path%></li>
				<li><%= link_to "Tablets", 	   tablets_path %></li>
				<li><%= link_to "Accesorios",  accessories_path%></li>
			</ul>
			</li>
			<li><a href="#">Nosotros</a>
				<ul>
					<li><a href="#">Quienes Somos</a></li>
					<li><a href="#">Contacto</a></li>
				</ul>
			</li>
			<li class="last"><a href="#"> Sucursales </a></li>
		</ul>
		</div>
        <%=yield%>
	  

	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>